version: '3'

services:
  postgres-master:
    image: postgres:14-alpine
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ticket-net
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"
    networks:
      - ticket-net
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - ticket-net

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.2
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - infrastructure-net
#  kafka:
#    image: confluentinc/cp-kafka:7.3.2
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - infrastructure-net
#  postgres-slave1:
#    image: postgres:13
#    container_name: postgres-slave1
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydb
#      POSTGRES_REPLICATION_ROLE: slave
#      POSTGRES_MASTER_HOST: postgres-master
#    depends_on:
#      - postgres-master
#    volumes:
#      - postgres-slave1-data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    networks:
#      - postgres-net
#
#  postgres-slave2:
#    image: postgres:13
#    container_name: postgres-slave2
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydb
#      POSTGRES_REPLICATION_ROLE: slave
#      POSTGRES_MASTER_HOST: postgres-master
#    depends_on:
#      - postgres-master
#    volumes:
#      - postgres-slave2-data:/var/lib/postgresql/data
#    ports:
#      - "5434:5432"
#    networks:
#      - postgres-net
#
networks:
  ticket-net:
    driver: bridge

volumes:
  postgres-master-data:
  redis-data:
  minio-data:
#  postgres-slave1-data:
#  postgres-slave2-data:
