server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
  flyway:
    enabled: true
    locations: classpath:database/migrations
    baseline-on-migrate: true
    baseline-version: 1
spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
